services:
  client:
    container_name: dndnotes-client
    build:
      context: .
      target: production
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - BACKEND_URL=${BACKEND_URL}
    networks:
      - dndnotes-network

networks:
  dndnotes-network:
    external: true