services:
  client:
    container_name: dndnotes-client
    build:
      context: .
      target: production
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    volumes:
      - react-static:/usr/share/nginx/html
    ports:
      - "3000:80"
    restart: unless-stopped
    # environment:
    #   - NODE_ENV=production
    #   - REACT_APP_API_URL=${REACT_APP_API_URL}
    # env_file:
    #   - stack.env
    networks:
      - dndnotes-network

volumes:
  react-static:

networks:
  dndnotes-network:
    external: true